### ISSUE TITLE
northwind

### ISSUE THREAD

**Issue by MenacingDwarf** [valery-kirichenko/db#2]
Для sql нет скрипта, он не нужен что ль? Или тоже стоит добавить, для xml же ты добавил

**Comment by valery-kirichenko** [comment]
Если ты собрался разворачивать свой sql-сервер, то я могу добавить, конечно. Но по-моему это займет кучу времени и в целом бессмысленно. PostgreSQL сервер нам даст Коровкин, а для MySQL я уже развернул у себя (данные для доступа писал в вк)
